#=========================================
#APPLICATION NAME
#=========================================
spring.application.name=studentservice

#Name of the Application used in locks,monitoring,microservices
#=========================================
#SERVER CONFIGURATION
#=========================================

server.port=2026

#Defines the port number where the springboot application will run
#defalut 8080
#access using http://local host:2026/
#======================================
#DATABASE CONFIGURATION(FOR MYSQL)
#=====================================
spring.datasource.url=jdbc:mysql://localhost:3307/my_student_db_spring

#JDBC url for MYSQL connection
#Formate:jdbc:mysql://<>host/<>port/<>database_name

spring.datasource.username=root
#MYSQL username

spring.datasource.password=12345
#MYSQL password

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#MYSQL JDBC Driver(required to connect java with my sql)
#==========================================
#JPA/HIBERNATE CONFIGURATION
#=========================================
spring.jpa.hibernate.ddl-auto=update
#Automatically creates/update databse tables based on entity classes
#options:create,update,validate,none
spring.jpa.show-sql=true
#prints sql queries in te console(useful for debugging
# tells hibernate to use mysql specific syntax
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect